import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const pages = [
  { href: '/mint', title: 'Mint', description: 'Mint your NFTs' },
  { href: '/collection', title: 'Collection', description: 'Discover our collection' },
  { href: '/edit', title: 'Edit NFTs', description: 'Make your NFTs as your own' },
  // Add more pages as needed
];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hobos Forever</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to our NFT collection Page
        </h1>

        <div className={styles.grid}>
          {pages.map((page) => (
            <a key={page.href} className={styles.card} href={page.href}>
              <h2>{page.title} &rarr;</h2>
              <p>{page.description}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
